ALTER TABLE Versiones ADD CONSTRAINT CK_Versiones_idPelicula_idSerie CHECK ((CASE WHEN idPelicula IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN idSerie IS NOT NULL THEN 1 ELSE 0 END) = 1);
ALTER TABLE Compras ADD CONSTRAINT CK_Compras_idPelicula_idSerie CHECK ((CASE WHEN idPelicula IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN idSerie IS NOT NULL THEN 1 ELSE 0 END) = 1);
ALTER TABLE Rentas ADD CONSTRAINT CK_Rentas_idPelicula_idSerie CHECK ((CASE WHEN idPelicula IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN idSerie IS NOT NULL THEN 1 ELSE 0 END) = 1);
ALTER TABLE ContenidoAdicional ADD CONSTRAINT CK_ContenidoAdicional_idPelicula_idSerie CHECK ((CASE WHEN idPelicula IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN idSerie IS NOT NULL THEN 1 ELSE 0 END) = 1);



