ALTER TABLE Peliculas ADD CONSTRAINT FK_Peliculas_distribuidor FOREIGN KEY (distribuidor) REFERENCES Distribuidores(nombre);
ALTER TABLE Series ADD CONSTRAINT FK_Series_distribuidor FOREIGN KEY (distribuidor) REFERENCES Distribuidores(nombre);
ALTER TABLE Temporadas ADD CONSTRAINT FK_Temporadas_idSerie FOREIGN KEY (idSerie) REFERENCES Series(id);
ALTER TABLE Episodios ADD CONSTRAINT FK_Episodios FOREIGN KEY (idSerie, numeroTemporada) REFERENCES Temporadas(idSerie, numeroTemporada);
ALTER TABLE Versiones ADD CONSTRAINT FK_Versiones_idPelicula FOREIGN KEY (idProducto) REFERENCES Peliculas(id);
ALTER TABLE Versiones ADD CONSTRAINT FK_Versiones_idSeries FOREIGN KEY (idProducto) REFERENCES Series(id);
ALTER TABLE ContenidoAdicional ADD CONSTRAINT FK_ContenidoAdicional_idPelicula FOREIGN KEY (idProducto) REFERENCES Peliculas(id);
ALTER TABLE ContenidoAdicional ADD CONSTRAINT FK_ContenidoAdicional_idSeries FOREIGN KEY (idProducto) REFERENCES Series(id);
ALTER TABLE ActoresPeliculas ADD CONSTRAINT FK_ActoresPeliculas_idPelicula FOREIGN KEY (idPelicula) REFERENCES Peliculas(id);
ALTER TABLE ActoresSeries ADD CONSTRAINT FK_ActoresSeries_idSeries FOREIGN KEY (idSeries) REFERENCES Series(id);
ALTER TABLE Bibliotecas ADD CONSTRAINT FK_Bibliotecas FOREIGN KEY (idCuenta, nombrePerfil) REFERENCES Perfiles(idCuenta, nombre);
ALTER TABLE BibliotecasPeliculas ADD CONSTRAINT FK_BibliotecasPeliculas_idBiblioteca FOREIGN KEY (idBiblioteca) REFERENCES Bibliotecas(id);
ALTER TABLE BibliotecasPeliculas ADD CONSTRAINT FK_BibliotecasPeliculas_idPelicula FOREIGN KEY (idPelicula) REFERENCES Peliculas(id);
ALTER TABLE BibliotecasSeries ADD CONSTRAINT FK_BibliotecasSeries_idBiblioteca FOREIGN KEY (idBiblioteca) REFERENCES Bibliotecas(id);
ALTER TABLE BibliotecasSeries ADD CONSTRAINT FK_BibliotecasSeries_idSerie FOREIGN KEY (idSerie) REFERENCES Series(id);
ALTER TABLE Perfiles ADD CONSTRAINT FK_Perfiles_idCuenta FOREIGN KEY (idCuenta) REFERENCES Cuentas(id);
ALTER TABLE Compras ADD CONSTRAINT FK_Compras_idCuenta FOREIGN KEY (idCuenta) REFERENCES Cuentas(id);
ALTER TABLE Compras ADD CONSTRAINT FK_Compras_idPelicula FOREIGN KEY (idProducto) REFERENCES Peliculas(idPelicula);
ALTER TABLE Compras ADD CONSTRAINT FK_Compras_idSerie FOREIGN KEY (idProducto) REFERENCES Series(idSerie);
ALTER TABLE Rentas ADD CONSTRAINT FK_Rentas_idCuenta FOREIGN KEY (idCuenta) REFERENCES Cuentas(id);
ALTER TABLE Rentas ADD CONSTRAINT FK_Rentas_idPelicula FOREIGN KEY (idProducto) REFERENCES Peliculas(idPelicula);
ALTER TABLE Rentas ADD CONSTRAINT FK_Rentas_idSerie FOREIGN KEY (idProducto) REFERENCES Series(idSerie);
ALTER TABLE CodigosDeRegalo ADD CONSTRAINT FK_CodigosDeRegalo_idCuenta FOREIGN KEY (idCuenta) REFERENCES Cuentas(id);
ALTER TABLE CodigosDeRegalo ADD CONSTRAINT FK_CodigosDeRegalo_idPelicula FOREIGN KEY (idProducto) REFERENCES Peliculas(idPelicula);
ALTER TABLE CodigosDeRegalo ADD CONSTRAINT FK_CodigosDeRegalo_idSerie FOREIGN KEY (idProducto) REFERENCES Series(idSerie);
ALTER TABLE MetodosDePago ADD CONSTRAINT FK_MetodosDePago_idCuenta FOREIGN KEY (idCuenta) REFERENCES Cuentas(id);
ALTER TABLE GroupWatch ADD CONSTRAINT FK_GroupWatch FOREIGN KEY (perfil, perfilSincronizado) REFERENCES Perfiles(nombre, nombre);
ALTER TABLE GroupWatchPeliculas ADD CONSTRAINT FK_GroupWatchPeliculas_idGroupWatch FOREIGN KEY (idGroupWatch) REFERENCES GroupWatch(idGroupWatch);
ALTER TABLE GroupWatchPeliculas ADD CONSTRAINT FK_GroupWatchPeliculas_idPelicula FOREIGN KEY (idPeliculas) REFERENCES Peliculas(id);
ALTER TABLE GroupWatchSeries ADD CONSTRAINT FK_GroupWatchSeries_idGroupWatch FOREIGN KEY (idGroupWatch) REFERENCES GroupWatch(idGroupWatch);
ALTER TABLE GroupWatchSeries ADD CONSTRAINT FK_GroupWatchSeries_idSerie FOREIGN KEY (idSerie) REFERENCES Series(id);