-- Ciclo Uno
DROP TRIGGER TG_Peliculas_BI;
DROP TRIGGER TG_Series_BI;
DROP TRIGGER TG_Versiones_BI;
DROP TRIGGER TG_ContenidosAdicionales_BI;
DROP TRIGGER TG_Bibliotecas_BI;
DROP TRIGGER TG_Cuentas_BI;
DROP FUNCTION cifrado;
DROP TRIGGER TG_Operaciones_BI;
DROP TRIGGER TG_Operaciones_AI;
DROP TRIGGER TG_Operaciones_AU;
DROP TRIGGER TG_Operaciones_AD;
DROP TRIGGER TG_Compras_BI;
DROP TRIGGER TG_Rentas_BI;
DROP TRIGGER TG_Distribuidores_BI;
DROP TRIGGER TG_BibliotecasPeliculas_BI;
DROP TRIGGER TG_BibliotecasSeries_BI;
DROP TRIGGER TG_BibliotecasPeliculas_AUI;
DROP TRIGGER TG_BibliotecasSeries_AUI;

-- Ciclio Dos
DROP TRIGGER TG_Rentas_AI;
DROP TRIGGER TG_Rentas_AD;